name: danielnguyen/Teller Repo Updated Check

on:
  schedule:
    - cron:  '30 5 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./scripts/isRepoUpdated.sh https://api.github.com/repos/danielnguyen/Teller/commits/master
